### ISSUE TITLE
Das arm64 Image funktioniert nicht

### ISSUE THREAD

**Issue by omski** [DeBaschdi/docker.new-telerising-api#1]
Da die telerising API bisher nur als armhf 32-bi Variante exisitiert läuft diese nicht ohne weiteres auf einem arm 64-bit System. Grundsätzlich ist es jedoch möglich auch armhf Code auf einem 64-bit Linux OS laufen zu lassen. Folgende Anpassungen müssen dafür am Dockerfile vorgenommen werden:
...
ARG DEPENDENCIES="... libc6:armhf"
...
RUN dpkg --add-architecture armhf \
...
Ich erstelle einen PR dafür.

**Comment by DeBaschdi** [comment]
thx https://github.com/DeBaschdi/docker.new-telerising-api/pull/2/commits/58bb1eea334d0d68a4744c2ac5a119f5bfa937c0
