### ISSUE TITLE
Fix slow git clone times (we only need to pull the main branch)

### ISSUE THREAD

**Issue by bernhardberger** [DeBaschdi/docker.new-telerising-api#15]
I think it would suffice to only checkout the `main` branch like so:

`git clone -b main --single-branch https://github.com/sunsettrack4/telerising-api.git`

instead of pulling all the branches which will take a massive amount of time because of the hunddreds of MBs of binaries it needs to pull.

Change is to be made here:
https://github.com/DeBaschdi/docker.new-telerising-api/blob/main/root/telerising.update#L8

**Comment by DeBaschdi** [comment]
Fixed in 0.0.4
https://github.com/DeBaschdi/docker.new-telerising-api/commit/f18ab374fce960fe5e27d4da334b76c47e1af658
