### ISSUE TITLE
Funktioniert nicht auf Synology wegen Port 5000

### ISSUE THREAD

**Issue by m-O-rpheus** [DeBaschdi/docker.new-telerising-api#3]
Hallo,

Da das Synology NAS selbst Port 5000 verwendet. Kann der Docker Container nicht im Host Modus verwendet werden.

Im Bridged Modus habe ich jedoch keinen Zugriff mit TvHeadnend wegen dem IP Bereich 172.17.0.2.

Ein starten des Containers im Bridged Modus. Anpassen des Port's auf 8180 in der WebUI.  Und dann den Netzwerk Modus umstellen auf Host, führt dazu das der Container nicht mehr gestartet werden kann.

**Comment by DeBaschdi** [comment]
Hi, schau mal hier : 
https://www.kodinerds.net/index.php/Thread/68463-Docker-NEW-Telerising-API-Support-Thread/?postID=633179#post633179
